apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-demo-ui
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: on-premises
    namespace: axians-ocp-demo
  project: default
  source:
    path: src/apps/dev/ui
    repoURL: 'https://github.com/jhoeflaken/ocp-demo-config'
    targetRevision: master