apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-demo-backend
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: ocp-demo-dev
  project: default
  source:
    path: src/apps/dev/backend
    repoURL: 'https://github.com/jhoeflaken/ocp-demo-config'
    targetRevision: master
#    plugin:
#      name: argocd-vault-plugin
#      env:
#        - name: AVP_K8S_ROLE
#          value: vplugin
#        - name: AVP_TYPE
#          value: vault
#        - name: AVP_VAULT_ADDR
#          value: 'http://vault.vault.svc.cluster.local:8200'
#        - name: AVP_AUTH_TYPE
#          value: k8s