apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-demo
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ocp-demo
    name: in-cluster
  source:
    path: src/apps/dev
    repoURL: 'https://github.com/jhoeflaken/ocp-demo-cd.git'
    targetRevision: develop
  project: default